### PR TITLE
Way to avoid using global variables

### PR DESCRIPTION
**Pull request by MarcCote**

### CODE REVIEW

**Comment by ranveeraggarwal** [comment]
I had done the same before, but then I felt that keeping a state attribute for the class just for a very specific callback isn't a good idea. Should I keep one anyway?

Also, I'm thinking of putting all the callbacks outside the class definition, since we would want the button to be dynamic in definition.

**Comment by MarcCote** [comment]
I like how it is coming along with the Button class, btw.

Regarding your question, for me the variable `state` should represent the state the button is currently in. That would make more sense to keep it inside the object. Different buttons will have different states. Using global variable wouldn't allow us to do that.

That said, I think we should have a predefined number of states a button can have (e.g. pressed, hover, default, etc.). If it happens that a user wants more states, he could easily derived his on CustomButton class by subclassing our generic Button class.

What do you think?

**Comment by ranveeraggarwal** [comment]
Sounds like a great idea! I can probably write a stateChangeHandler of some
sort to handle this.
I'll put this in my next commit :)

**Comment by MarcCote** [comment]
Alright, keep up the good work. :+1:

**Comment by MarcCote** [comment]
Oh, and while at it. We could keep the a list of `vtkImageDataGeometryFilter` objects instead of `fnames`. That way, we could simply call the `self.actor.GetMapper().SetInputConnection(...)` method without having to reload the PNGs from the disk each time the state changes.

**Comment by ranveeraggarwal** [comment]
Sure, so here's an idea. During button definition, the parameters can be
the number of states and an list containing the filenames. That way, I can
pre compute the `vtkImageDataGeometryFilter` objects while initialisation.

**Comment by MarcCote** [comment]
My concern with that approach is how could we associated a specific state/icon to specific event? For example, I want the button to glow (brighter icon) only when the mouse is hovering it.

I think we need more control. I'm just thinking out loud here, what about the following:

``` python
button = Button()
button.icon_default = "fig1.png"
button.icon_hovering = "fig2.png"
button.icon_onclick = "fig3.png"
```

where `button.icon_*` would be properties and when assigning a value to them we would create/update its corresponding `vtkImageDataGeometryFilter` object.

**Comment by ranveeraggarwal** [comment]
Here's what I was thinking. We have a list of filenames, and we create a button out of it:

```
state_list = ["fig1.png", "fig2.png", "fig3.png"]
button = Button(state_list)
```

In the button class, I have a variable called state. Now I write a `state_handler` like this:

```
if self.state == len(self.state_list):
    self.state = 0
if self.state == 0:
    self.actor.GetMapper().SetInputConnection(vtkImageDataGeometryFilter for file 1)
elif self.state == 1:
    self.actor.GetMapper().SetInputConnection(vtkImageDataGeometryFilter for file 2)
...
```

And the callback function (outside the class definition) can work like this:

```
def callback_function(*args, **kwargs):
    if button.state == 0:
        foo1()
    elif button.state == 1:
        foo2()
    ...
```

Basically, the icon/function at a particular state is the index of the png file `state_list` list

**Comment by MarcCote** [comment]
How would you know which state corresponds to the hovering and which one to the pressed event?

**Comment by MarcCote** [comment]
We should probably use a dictionary to store callbacks, that way we could simply do `self.callbacks[button.state]()`. We could probably do the same for the `vtkImageDataGeometryFilter` objects `self.actor.GetMapper().SetInputConnection(self.geometry_filters[self.state])`
Edit: No need for if-elif-else that way.

**Comment by ranveeraggarwal** [comment]
For that, we can add a different callback for hover and pressed events, and push them in the `event_set`. 
Oh, now I see what you mean. So you're saying that since hovering and pressing are common events, the states for them _should_ be predefined in the class. 

I'll do so, and the extension I'm talking can be done in a custom button class inherited from `Button` as you said.

**Comment by MarcCote** [comment]
Actually, your extension, the `StateHandler`, could be the mechanism used under the hood in the `Button` class. By that I mean, we could have a `self.state_manager` that would be responsible for calling the right callback and managing the states. If we do it right, it should be flexible enough to be used in other UI components.

**Comment by ranveeraggarwal** [comment]
Alright, I'll push an implementation and then let's discuss it further :)

**Comment by MarcCote** [comment]
Sounds good.

**Comment by Garyfallidis** [comment]
@ranveeraggarwal and @MarcCote A few important points here. 

1) Definitely try to reduce global variables. Agree with Marc-Alex.

2) All the textures (PNGs) of a button need to be loaded upon initialization. All modify should do is change the texture or update the mapper. Shouldn't be reading anything from the disk. I see you discussed that already. 

3) Get used to pep8 coding style (let me know if you need documentation for that). Please use an automatic corrector for pep 8 for your editor. 

4) EventsSet doesn't make much sense to be an independent object as all it does is to output a simple list of tuples. That could be an input of the Button itself. It reads well in the code but we need to think if we really need that. 

5) I wonder if the name state helps the API design discussion. For me things are more simple. For me all we have for the button is a list of textures (icons). To access each texture we need to know the id of the texture. To change how the button looks, all we need is the id of another texture.  What I mean here is that the events (hovering, press etc) are independent from what the button looks and these two shouldn't be mixed in the design. 

I would personally do this 

```
class UI(object):
    self.actor = None 

class Button(UI):
     # here i use the name icon for simplicity but we could use representation or face or something else.
    def __init__(self.icon_filenames):
        self.icon_ids, self.icon_id, self.actor = self.build(...)
    def build(self):
        # build textures and return default actor, ids and id (current id)
    def add_callback(self, event_type, callback):
        self.actor.AddObserver(event_type, callback)
    def set(self, icon_id): # this similar to what you called modify
        # update actor to show the new_id i.e. a new texture

```

Here is an example (for a standard music player button). Goes from play to pause to stop and back.

```
cube = Button(['play.png', 'stop.png', 'pause.png'])

def left_button_press_callback():
    if cube.icon_id == 0: #play
        cube.set(1)
    if cube.icon_id == 1: #pause
        cube.set(2)
    if cube.icon_id == 2: #stop
        cube.set(0)

cube.add_callback("LeftButtonPressEvent", left_button_press_callback)
```

So, I don't think that we need something like that. 

```
button.icon_default = "fig1.png"
button.icon_hovering = "fig2.png"
button.icon_onclick = "fig3.png"
```

Or a state manager. But please correct me if I miss something.

Let's imagine a harder case where play glows when we hover on top of it. We can say that glow now means changes color. Be happy to try to change the color of an actor on mouse move. For that we need to add a different callback. Remember that "play" has icon_id 0.

```
def mouse_move_callback():
    if cube.icon_id == 0:
        cube.actor.GetProperty().SetColor(1, 0, 0)

cube.add_callback("MouseMoveEvent", mouse_move_callback)
```

The effect of the above would be that only the button with the "play" icon will glow (change color). Nothing will happen when we move the mouse on top of the "stop" or "pause" representation of the button.

I hope this makes sense. Because we need to move relatively fast at this stage let me know if you need a quick hangout before our regular meeting.  And please let me know if what I say here is clear. 

GGT!!! :)

**Comment by MarcCote** [comment]
I think that if we want something more user-friendly, we need names. Ideally, the user shouldn't have to know about the `vtkCommand`'s names (e.g. MouseMoveEvent, LeftButtonPressEvent). It would be better if he could do something as simple as:

``` python
button.onhover = callback1
button.onclick = callback2
```

Maybe for now it is alright to use IDs and follow @Garyfallidis's approach as it is more flexible.

Note that the approach above could lead to code duplication. For instance, if you have two buttons that have the same behavior (but a different location), you'll end up with two highly similar callback functions because `cube` needs to refer to the right object and be part of the local variables.

In fact, we should check what parameters a callback function receives. If the button object is there, that might simplify a lot of things (e.g. avoid duplicating callback functions).

Also, personally, I prefer the term `state` over `icon_id`.

**Comment by ranveeraggarwal** [comment]
@MarcCote we can probably create a generic button class in the way @Garyfallidis proposed and then inherit that (say `ButtonHoverable`), keeping a few extra variables to implement hover and click. It'll just have two extra built-in callback functions

**Pull request closed without merging**
