### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by MarcCote**
I started to make some refactoring so it resembles more `LineSlider2D`. Let me know what you think. If you like it you can go ahead and merge it, the test is supposes to pass. There is some docstring that still need to be modified but we can do it directly in your PR.

### CODE REVIEW

**Comment by ranveeraggarwal** [comment]
@MarcCote I'm not sure why the test 13 is failing here. There's apparently some deprecation warning that increases the log file size.

**Comment by MarcCote** [comment]
Yeah it has happened to me too. Just re launch the test.

**Comment by ranveeraggarwal** [comment]
@MarcCote ah cool.

**Comment by MarcCote** [comment]
I think if we rebase on master it will be fine. See https://github.com/nipy/dipy/pull/1229
I would say, review this PR and let me know what you think of the modifications. If you like them merge it then rebase your branch on master.

**Comment by ranveeraggarwal** [comment]
lgtm, I'll merge this and add a couple of fixes before you can approve https://github.com/nipy/dipy/pull/1222

**Pull request merged**
